name: conda_env

channels:
  - defaults

dependencies:
  - python=3.9
  - pip
  - pip:
      - matplotlib==3.7.5
      - qiskit>=1.0.0
      - qiskit_algorithms==0.3.0
      - qiskit_ibm_runtime==0.22.0
      - qiskit_ibm_provider==0.10.0
      - qiskit_machine_learning==0.7.2
      - torch==2.2.1
      - mlflow>=2.10.1
      - git+https://github.com/SaashaJoshi/piQture.git