name: MLflow Workflow

on:
  workflow_dispatch:

jobs:
  mlflow:

    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run MLflow Script for QCNN
        run: |
          mlflow run scripts/qcnn_script.py
#          mlflow run . --file Mlproject --experiment-name "Your Experiment Name"

#  register_model:
#      needs: mlflow
#      runs-on: ubuntu-latest
#      if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
#      steps:
#        - name: Register model
#          run: |
#            if [ CONDITION_TO_REGISTER_MODEL ]; then
#              mlflow register model -m "runs:/<run_id>/model_name" -n "Registered Model Name"
#            else
#              echo "Model registration not required."
#            fi

#      - name: Log with MLflow and Register Model
#        run: |
#          mlflow run . --experiment-name=${{ secrets.MLFLOW_EXPERIMENT_NAME }} --no-conda
#          mlflow models register -m "runs:/${{ github.sha }}/model" -n "your_model_name" -r "your_model_version" --experiment-name="${{ secrets.MLFLOW_EXPERIMENT_NAME }}" --no-conda
#        env:
#          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
#          MLFLOW_REGISTRY_URI: ${{ secrets.MLFLOW_REGISTRY_URI }}
#          MLFLOW_EXPERIMENT_NAME: ${{ secrets.MLFLOW_EXPERIMENT_NAME }}
